menus:
#  home: /
#  about: /about/
#  tags: /tags/
#  archives: /archives/

social:
#  GitHub: https://github.com/w4ngzhen/hexo-theme-brief || fa fa-github
#  RSS: /atom.xml || fa fa-rss

favicon:
#  small: /images/icon_16x16.png
#  medium: /images/icon_32x32.png
#  apple_touch_icon: /images/icon_32x32.png
#  safari_pinned_tab: /images/icon_32x32.png