menus:
  主页: /
#  关于: /about/
#  分类: /categories/
#  标签: /tags/
#  友情链接: /links/
# 上述 关于、分类、标签、友链等路径，
# 需要使用者在Hexo项目根目录/source目录中创建对应的目录，并在目录中创建index.md并设置layout
# 可参考 https://github.com/w4ngzhen/brief-theme-example

social:
#  GitHub: https://github.com/w4ngzhen/hexo-theme-brief || fa fa-github

favicon:
  small: /images/icon.svg
  medium: /images/icon.svg
  apple_touch_icon: /images/icon.svg
  safari_pinned_tab: /images/icon.svg